import os
import logging
from openai import OpenAI

logger = logging.getLogger(__name__)

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
if not OPENAI_API_KEY:
    logger.warning("OPENAI_API_KEY is not set. Long-form rewrite will fall back to raw text.")

client = OpenAI(api_key=OPENAI_API_KEY)


def rewrite_to_long_form(title: str, raw_text: str, sport: str = "sports") -> str:
    """
    Rewrite short news text into a long-form sports article.
    Uses gpt-4o-mini (jeftin i dobar).
    If OpenAI fails (quota, rate limit, etc.), returns the original raw_text.
    """
    if not OPENAI_API_KEY:
        return raw_text or ""

    if not raw_text:
        return raw_text or ""

    prompt = f"""
You are a professional sports journalist for a premium portal called NinkoSports.

Write a detailed, engaging article based on the following information.

Sport: {sport}
Title: {title}

Original text:
{raw_text}

Requirements:
- Keep it factual. Do NOT invent fake transfers, results, injuries, or quotes.
- Structure: short intro, clear middle, and short conclusion.
- Use paragraphs and simple, direct English.
- Neutral, professional tone but dynamic and interesting.
- Do NOT mention that this text was generated by AI.
"""

    try:
        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[
                {
                    "role": "system",
                    "content": "You are an expert sports journalist for NinkoSports."
                },
                {
                    "role": "user",
                    "content": prompt
                },
            ],
            temperature=0.6,
            max_tokens=700,  # limitiramo da ne troši bezveze
        )
        content = response.choices[0].message.content
        if content:
            return content.strip()
        return raw_text or ""
    except Exception as e:
        logger.error(f"OpenAI rewrite error: {e}")
        return raw_text or ""
