import os
import logging

from openai import OpenAI
import openai

logger = logging.getLogger(__name__)

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

if not OPENAI_API_KEY:
    logger.warning("OPENAI_API_KEY is not set. Long-form rewrite will fall back to raw text.")

client = OpenAI(api_key=OPENAI_API_KEY)


def rewrite_to_long_form(title: str, raw_text: str, sport: str = "sports") -> str:
    """
    Rewrite short news text into a long-form sports article.
    If OpenAI fails (quota, rate limit, etc.), returns the original raw_text.
    """
    if not OPENAI_API_KEY:
        return raw_text

    prompt = f"""
You are a professional sports journalist for a premium portal called AllBall Sports.

Write a detailed, engaging long-form article based on the following information.

Sport: {sport}
Title: {title}

Original text:
{raw_text}

Requirements:
- Keep it factual. Do not invent fake transfers, results, or quotes.
- Add structure: short intro, main body, and short conclusion.
- Use clear paragraphs and simple, direct English.
- Neutral, professional tone, but dynamic and interesting.
- Do not mention that this text was generated by AI.
"""

    try:
        response = client.chat.completions.create(
            model="gpt-4.1-mini",
            messages=[
                {"role": "system", "content": "You are an expert sports journalist."},
                {"role": "user", "content": prompt},
            ],
            temperature=0.7,
        )
        return response.choices[0].message.content.strip()
    except openai.RateLimitError as e:
        logger.error(f"OpenAI quota / rate limit error: {e}")
        return raw_text
    except Exception as e:
        logger.error(f"OpenAI rewrite error: {e}")
        return raw_text
